---
- name: "An EAP Playbook"
  hosts: "{{ wildfly_ansible_hosts | default('localhost') }}"
  gather_facts: no
  vars:
    - ansible_distribution: Red Hat Enterprise Linux # just because this playbook does not gather facts
    - jboss: {
        config: standalone.xml,
        bind_addr: 127.0.0.1,
        package_name: eap7-wildfly,
        port_shift: 0,
        home: '/opt/rh/eap7/root/usr/share/wildfly',
        jvm_memory: 512m,
        management_username: admin,
        management_password: r3dh4t
        }
  roles:
    - redhat-cop.jcliff
  tasks:

    # the yum: is quite slow to assert a package is already installed,
    # this is just a workaround to speed things up
    - name: "Test if package {{ jboss.package_name }} is already installed"
      command: rpm -q {{ jboss.package_name }}
      args:
        warn: no
      register: rpm_info
      changed_when: rpm_info.failed

    - name: "Install EAP 7"
      yum:
        name: "{{ jboss.package_name }}"
        state: "installed"
      when: rpm_info.failed

    - name: "Created config directory for jboss-eap7"
      file:
        path: /etc/jboss-eap7/
        state: directory
        group: jboss
        owner: jboss

    - name: "Deploy configuration for jboss-eap7"
      template:
        src: templates/eap7-standalone.service.j2
        dest: /usr/lib/systemd/system/eap7-standalone.service
        group: jboss
        owner: jboss

    - name: "Deploy init script for jboss-eap7"
      copy:
        src: files/jboss-eap7
        dest: /etc/init.d/jboss-eap7
        owner: root
        group: root
        mode: 0755

    - name: "Deploy creds for jcliff script for jboss-eap7"
      template:
        src: "templates/{{ item }}.j2"
        dest: "{{ jboss.home }}/standalone/configuration/{{ item }}"
        owner: jboss
        group: jboss
        mode: 0600
      loop:
        - mgmt-groups.properties
        - mgmt-users.properties

    - name: "Ensure JBoss EAP 7 is running"
      service:
        name: 'eap7-standalone'
        state: started
        enabled: yes

    - name: "Tuning Wildfly using JCliff"
      jcliff:
        wfly_home: "{{ jboss.home }}"
        #rule_file: "{{ path_to_custom_rules }}"
        management_username: "{{ jboss.management_username }}"
        management_password: "{{ jboss.management_password }}"
        subsystems:
          - system_props:
              - name: jcliff.enabled
                value: true
