---
- name: "An EAP Playbook"
  hosts: "{{ wildfly_ansible_hosts | default('localhost') }}"
  gather_facts: yes
  vars:
    - ansible_distribution: Red Hat Enterprise Linux # just because this playbook does not gather facts
    - jboss: {
        config: standalone.xml,
        bind_addr: "{{ ansible_default_ipv4.address | default('127.0.0.1') }}",
        port: 80,
        package_name: eap7-wildfly,
        service_name: 'eap7-standalone',
        home: '/opt/rh/eap7/root/usr/share/wildfly',
        management_username: admin,
        management_password: r3dh4t,
        time2boot: "{{ eap7_time_to_boot | default('10') }}"
      }
    - path_to_custom_rules: "{{ playbook_dir }}/files/rules/"
    - app: {
        folder: /var/www/html/app
    }
  roles:
    - redhat-cop.jcliff
  tasks:

    # the yum: is quite slow to assert a package is already installed,
    # this is just a workaround to speed things up
    - name: "Test if package {{ jboss.package_name }} is already installed"
      command: rpm -q {{ jboss.package_name }}
      args:
        warn: no
      register: rpm_info
      changed_when: rpm_info.failed
      ignore_errors: true

    - name: "Install EAP 7"
      yum:
        name: "{{ jboss.package_name }}"
        state: "installed"
      when: rpm_info.failed

    - name: "Configure SystemD service for EAP7"
      template:
        src: templates/eap7-standalone.service.j2
        dest: /usr/lib/systemd/system/eap7-standalone.service
        group: jboss
        owner: jboss

    - name: "Deploy init script for jboss-eap7"
      copy:
        src: files/jboss-eap7
        dest: /etc/init.d/jboss-eap7
        owner: root
        group: root
        mode: 0755

    - name: "Deploy creds for jcliff script for jboss-eap7"
      template:
        src: "templates/{{ item }}.j2"
        dest: "{{ jboss.home }}/standalone/configuration/{{ item }}"
        owner: jboss
        group: jboss
        mode: 0600
      loop:
        - mgmt-groups.properties
        - mgmt-users.properties

    - name: "Ensure JBoss EAP 7 is running"
      service:
        name: "{{ jboss.service_name }}"
        state: restarted
        enabled: yes

    - name: "Wait for EAP7 to be up"
      wait_for:
        delay: "{{ jboss.time2boot }}"
        port: "{{ jboss.port }}"
        host: "{{ jboss.bind_addr }}"

    - name: "Ensure the App folder exists"
      file:
        path: "{{ app.folder }}"
        state: directory
        group: jboss
        owner: jboss

    - name: "Tuning Wildfly using JCliff"
      jcliff:
        wfly_home: "{{ jboss.home }}"
        rule_file: "{{ path_to_custom_rules }}"
        management_username: "{{ jboss.management_username }}"
        management_password: "{{ jboss.management_password }}"
        subsystems:
          - system_props:
              - name: jcliff.enabled
                value: true
      notify: "Restart EAP7 Server"

  handlers:
    - name: "Restart EAP7 Server"
      service:
        name: "{{ jboss.service_name }}"
        state: restarted
        daemon_reload: yes
